logging:
  level:
    org.springframework.cloud.gateway: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: levi
          uri: http://localhost:8100/levi
          predicates:
            - Path=/levi/**
        - id: alvin
          uri: http://localhost:8200/alvin
          predicates:
            - Path=/alvin/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: bertolt
server:
  port: 8000
  servlet:
    context-path: /bertolt
mybatis:
  mapper-locations: classpath:/sqlmap/*.xml
module:
  ymir: http://localhost:8080/ymir
  armin: http://localhost:8180/armin
